// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rest_api_labb_minimalapi.Data;

#nullable disable

namespace rest_api_labb_minimalapi.Migrations
{
    [DbContext(typeof(RestLabbDbContext))]
    partial class RestLabbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestPerson", b =>
                {
                    b.Property<int>("InterestsInterestId")
                        .HasColumnType("int");

                    b.Property<int>("PeoplePersonId")
                        .HasColumnType("int");

                    b.HasKey("InterestsInterestId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("InterestPerson");

                    b.HasData(
                        new
                        {
                            InterestsInterestId = 1,
                            PeoplePersonId = 1
                        },
                        new
                        {
                            InterestsInterestId = 4,
                            PeoplePersonId = 1
                        },
                        new
                        {
                            InterestsInterestId = 2,
                            PeoplePersonId = 2
                        },
                        new
                        {
                            InterestsInterestId = 3,
                            PeoplePersonId = 3
                        });
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("InterestDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            InterestDescription = "Writing and developing software applications",
                            InterestName = "Programming"
                        },
                        new
                        {
                            InterestId = 2,
                            InterestDescription = "Capturing moments through a camera lens",
                            InterestName = "Photography"
                        },
                        new
                        {
                            InterestId = 3,
                            InterestDescription = "Preparing and experimenting with food recipes",
                            InterestName = "Cooking"
                        },
                        new
                        {
                            InterestId = 4,
                            InterestDescription = "Playing video games across various platforms",
                            InterestName = "Gaming"
                        },
                        new
                        {
                            InterestId = 5,
                            InterestDescription = "Exploring books and literature",
                            InterestName = "Reading"
                        },
                        new
                        {
                            InterestId = 6,
                            InterestDescription = "Walking and exploring nature trails",
                            InterestName = "Hiking"
                        },
                        new
                        {
                            InterestId = 7,
                            InterestDescription = "Playing instruments or listening to music",
                            InterestName = "Music"
                        },
                        new
                        {
                            InterestId = 8,
                            InterestDescription = "Visiting new places and experiencing cultures",
                            InterestName = "Traveling"
                        },
                        new
                        {
                            InterestId = 9,
                            InterestDescription = "Growing plants and maintaining gardens",
                            InterestName = "Gardening"
                        },
                        new
                        {
                            InterestId = 10,
                            InterestDescription = "Exercising and maintaining physical health",
                            InterestName = "Fitness"
                        });
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            InterestId = 1,
                            LinkUrl = "https://github.com/anna-codes",
                            PersonId = 1
                        },
                        new
                        {
                            LinkId = 2,
                            InterestId = 2,
                            LinkUrl = "https://instagram.com/erik-photos",
                            PersonId = 2
                        },
                        new
                        {
                            LinkId = 3,
                            InterestId = 3,
                            LinkUrl = "https://recipes.com/maria-kitchen",
                            PersonId = 3
                        },
                        new
                        {
                            LinkId = 4,
                            InterestId = 4,
                            LinkUrl = "https://twitch.tv/anna-gaming",
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "070-1234567"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Erik",
                            LastName = "Johansson",
                            PhoneNumber = "070-2345678"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Maria",
                            LastName = "Nilsson",
                            PhoneNumber = "070-3456789"
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Oscar",
                            LastName = "Lindberg",
                            PhoneNumber = "070-4567890"
                        },
                        new
                        {
                            PersonId = 5,
                            FirstName = "Sofia",
                            LastName = "Andersson",
                            PhoneNumber = "070-5678901"
                        });
                });

            modelBuilder.Entity("InterestPerson", b =>
                {
                    b.HasOne("rest_api_labb_minimalapi.Models.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rest_api_labb_minimalapi.Models.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Link", b =>
                {
                    b.HasOne("rest_api_labb_minimalapi.Models.Entities.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rest_api_labb_minimalapi.Models.Entities.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("rest_api_labb_minimalapi.Models.Entities.Person", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
